runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: dist/aerosports-website/index.html
  upload: dist/aerosports-website/index.html

- url: /
  static_dir: dist/aerosports-website