runtime: python27
api_version: 1
threadsafe: true

env_variables:
  environment: "--prod"
  
handlers:
  - url: /
    secure: always
    static_files: dist/aerosports-website/index.html
    upload: dist/aerosports-website/index.html

  #  Routing rules for resources, css, js, images etc. Any file with format filename.ext
  - url: /(.*\.(.+))$
    secure: always
    static_files: dist/aerosports-website/\1
    upload: dist/aerosports-website/(.*\.(.+))$

  #  Routing rule for Angular Routing
  - url: /(.*)
    secure: always
    static_files: dist/aerosports-website/index.html
    upload: dist/aerosports-website/index.html